spring:
  application:
    name: didp-messaging

server:
  error:
    include-message: always
  port: 9092
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: health

didp:
  messaging:
    security:
      signature:
        ttl: PT1M
        enabled: false # Disable until Mobile app is ready
        algorithm: EdDSA